TestApp/Models/Bims2ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestApp.Models
{
    public class Bims2ViewModel
    {
        public Nullable<int> StatementNum { get; set; }
        public string StatementDate { get; set; }
        public long APN { get; set; }
        public string Property_Address { get; set; }
        public string Property_City_State_Zip { get; set; }
        public Nullable<int> RSO_Exemptions { get; set; }
        public Nullable<int> SCEP_Exmpetions { get; set; }
        public string IS_RSO { get; set; }
        public string IS_SCEP { get; set; }
        public string RSO_Invoice_Num { get; set; }
        public string SCEP_Invoice_Num { get; set; }
        public Nullable<int> Total_Units { get; set; }
        public Nullable<int> RSO_Units_Billed { get; set; }
    }
}

TestApp/Models/bims2.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bims2
    {
        public int id { get; set; }
        public Nullable<int> StatementNum { get; set; }
        public string StatementDate { get; set; }
        public long APN { get; set; }
        public string Property_Address { get; set; }
        public string Property_City_State_Zip { get; set; }
        public Nullable<int> RSO_Exemptions { get; set; }
        public Nullable<int> SCEP_Exmpetions { get; set; }
        public string IS_RSO { get; set; }
        public string IS_SCEP { get; set; }
        public string RSO_Invoice_Num { get; set; }
        public string SCEP_Invoice_Num { get; set; }
        public Nullable<int> Total_Units { get; set; }
        public Nullable<int> RSO_Units_Billed { get; set; }
        public Nullable<int> SCEP_Units_Billed { get; set; }
        public string is_active { get; set; }
        public Nullable<int> AddressMasterId { get; set; }
    }
}

TestApp/Controllers/bims2Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestApp.Models;

namespace TestApp.Controllers
{
    public class bims2Controller : Controller
    {
        private hcid_lookupEntities db = new hcid_lookupEntities();

        // GET: bims2
        public ActionResult Index(string StreetAddress, string CityState)
        {
            return View(db.bims2.Where(x => x.Property_Address == StreetAddress).ToList());
        }

        // GET: bims2/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bims2 bims2 = db.bims2.Find(id);
            if (bims2 == null)
            {
                return HttpNotFound();
            }
            return View(bims2);
        }

        // GET: bims2/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: bims2/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,StatementNum,StatementDate,APN,Property_Address,Property_City_State_Zip,RSO_Exemptions,SCEP_Exmpetions,IS_RSO,IS_SCEP,RSO_Invoice_Num,SCEP_Invoice_Num,Total_Units,RSO_Units_Billed,SCEP_Units_Billed,is_active,AddressMasterId")] bims2 bims2)
        {
            if (ModelState.IsValid)
            {
                db.bims2.Add(bims2);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bims2);
        }

        // GET: bims2/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bims2 bims2 = db.bims2.Find(id);
            if (bims2 == null)
            {
                return HttpNotFound();
            }
            return View(bims2);
        }

        // POST: bims2/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,StatementNum,StatementDate,APN,Property_Address,Property_City_State_Zip,RSO_Exemptions,SCEP_Exmpetions,IS_RSO,IS_SCEP,RSO_Invoice_Num,SCEP_Invoice_Num,Total_Units,RSO_Units_Billed,SCEP_Units_Billed,is_active,AddressMasterId")] bims2 bims2)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bims2).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bims2);
        }

        // GET: bims2/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bims2 bims2 = db.bims2.Find(id);
            if (bims2 == null)
            {
                return HttpNotFound();
            }
            return View(bims2);
        }

        // POST: bims2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bims2 bims2 = db.bims2.Find(id);
            db.bims2.Remove(bims2);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestApp/Views/bims2/Create.cshtml
@model TestApp.Models.bims2

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>bims2</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StatementNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StatementNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StatementNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatementDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StatementDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StatementDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.APN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.APN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.APN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Property_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_City_State_Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property_City_State_Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Property_City_State_Zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RSO_Exemptions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RSO_Exemptions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RSO_Exemptions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SCEP_Exmpetions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SCEP_Exmpetions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SCEP_Exmpetions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IS_RSO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IS_RSO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IS_RSO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IS_SCEP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IS_SCEP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IS_SCEP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RSO_Invoice_Num, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RSO_Invoice_Num, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RSO_Invoice_Num, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SCEP_Invoice_Num, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SCEP_Invoice_Num, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SCEP_Invoice_Num, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total_Units, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total_Units, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total_Units, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RSO_Units_Billed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RSO_Units_Billed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RSO_Units_Billed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SCEP_Units_Billed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SCEP_Units_Billed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SCEP_Units_Billed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.is_active, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.is_active, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressMasterId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressMasterId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressMasterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestApp/Views/bims2/Delete.cshtml
@model TestApp.Models.bims2

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>bims2</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StatementNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatementNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatementDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatementDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.APN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.APN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_City_State_Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_City_State_Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RSO_Exemptions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RSO_Exemptions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SCEP_Exmpetions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SCEP_Exmpetions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IS_RSO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IS_RSO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IS_SCEP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IS_SCEP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RSO_Invoice_Num)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RSO_Invoice_Num)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SCEP_Invoice_Num)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SCEP_Invoice_Num)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_Units)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_Units)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RSO_Units_Billed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RSO_Units_Billed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SCEP_Units_Billed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SCEP_Units_Billed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressMasterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressMasterId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TestApp/Views/bims2/Details.cshtml
@model TestApp.Models.bims2

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>bims2</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StatementNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatementNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatementDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatementDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.APN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.APN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_City_State_Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_City_State_Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RSO_Exemptions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RSO_Exemptions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SCEP_Exmpetions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SCEP_Exmpetions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IS_RSO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IS_RSO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IS_SCEP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IS_SCEP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RSO_Invoice_Num)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RSO_Invoice_Num)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SCEP_Invoice_Num)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SCEP_Invoice_Num)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_Units)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_Units)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RSO_Units_Billed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RSO_Units_Billed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SCEP_Units_Billed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SCEP_Units_Billed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressMasterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressMasterId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TestApp/Views/bims2/Index.cshtml
@model IEnumerable<TestApp.Models.bims2>

@{
    ViewBag.Title = "Index";
}

<h2>Lookup Tool</h2>
<b>Fill in your keywords and hit "Search"</b>
<br />
@using (Html.BeginForm("Index", "bims2", FormMethod.Get))
{
    <p>Street Address</p>@Html.TextBox("StreetAddress")
    <p>City, State, Zip Code</p>@Html.TextBox("CityState")
    <input type="submit" value="Search" />
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<H3>List View</H3>
@foreach (var item in Model)
{
<p>
    <b>Statement Num: </b>
    @Html.DisplayFor(modelItem => item.StatementNum)
</p>
<p>
    <b>Statement Date: </b>
    @Html.DisplayFor(modelItem => item.StatementDate)
</p>
<p>
    <b>APN: </b>
    @Html.DisplayFor(modelItem => item.APN)
</p>
<p>
    <b>Property Address: </b>
    @Html.DisplayFor(modelItem => item.Property_Address)
</p>
<p>
    <b>Property_City_State_Zip: </b>
    @Html.DisplayFor(modelItem => item.Property_City_State_Zip)
</p>
<p>
    <b>RSO_Exemptions: </b>
    @Html.DisplayFor(modelItem => item.RSO_Exemptions)
</p>
<p>
    <b>IS_RSO: </b>
    @Html.DisplayFor(modelItem => item.IS_RSO)
</p>
<p>
    <b>IS_SCEP: </b>
    @Html.DisplayFor(modelItem => item.IS_SCEP)
</p>
<p>
    <b>RSO_Invoice_Num: </b>
    @Html.DisplayFor(modelItem => item.RSO_Invoice_Num)
</p>
<p>
    <b>SCEP_Invoice_Num: </b>
    @Html.DisplayFor(modelItem => item.SCEP_Invoice_Num)
</p>
<p>
    <b>Total_Units: </b>
    @Html.DisplayFor(modelItem => item.Total_Units)
</p>
<p>
    <b>RSO_Units_Billed: </b>
    @Html.DisplayFor(modelItem => item.RSO_Units_Billed)
</p>
<p>
    <b>SCEP_Units_Billed: </b>
    @Html.DisplayFor(modelItem => item.SCEP_Units_Billed)
</p>
<p>
    <b>is_active: </b>
    @Html.DisplayFor(modelItem => item.is_active)
</p>
<p>
    <b>AddressMasterId: </b>
    @Html.DisplayFor(modelItem => item.AddressMasterId)
</p>
}
<H3>Table View</H3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StatementNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StatementDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.APN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Property_Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Property_City_State_Zip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RSO_Exemptions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SCEP_Exmpetions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IS_RSO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IS_SCEP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RSO_Invoice_Num)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SCEP_Invoice_Num)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total_Units)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RSO_Units_Billed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SCEP_Units_Billed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.is_active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressMasterId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StatementNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatementDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.APN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Property_Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Property_City_State_Zip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RSO_Exemptions)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SCEP_Exmpetions)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IS_RSO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IS_SCEP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RSO_Invoice_Num)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SCEP_Invoice_Num)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total_Units)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RSO_Units_Billed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SCEP_Units_Billed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.is_active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddressMasterId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>